CI: rework which part is doing which task

diff --git a/get b/get
--- a/get
+++ b/get
@@ -1,11 +1,11 @@
 #!/bin/sh
 build_dep() {
-	# SDL3 build-dep
-	sudo apt-get install build-essential cmake debhelper fcitx-libs-dev glslang-tools libasound2-dev libdbus-1-dev libdecor-0-dev libdrm-dev libegl-dev libgbm-dev libgl-dev libgles-dev libibus-1.0-dev libpipewire-0.3-dev libpulse-dev libsndio-dev libudev-dev liburing-dev libvulkan-dev libwayland-dev libx11-dev libxcursor-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxss-dev libxt-dev libxv-dev libxxf86vm-dev pkgconf wayland-protocols xxd graphviz doxygen
-	# missing libusb2-dev libusbhid-dev but build don't fail
-	( cd lib/platform/sdl3-deb/libsdl3-* && LANG=C dpkg-buildpackage -uc -us && rm -f libsdl3-doc* libsdl3-tests* )
+	case "$1" in
+		Debug|Release) _prebuilt_systemlibs; sources ;;
+		SystemLibs) _build_systemlibs ;;
+		*) echo "Bad BUILD_TYPE, should be (Debug|Release|SystemLibs)" >&2; exit 1 ;;
+	esac
 }
-
 cflags() {
 	case "$1" in
 		Debug)          solution="-ggdb3 -O0 -D_DEBUG" ;;
@@ -30,23 +30,48 @@ name() {
 }
 prettyos() {
 	case $(uname -s) in
-		Linux)      os="Linux" ;;
+		Linux)      os="$( . /etc/os-release && echo $ID-$VERSION_CODENAME )" ;;
 		Darwin)     os="MacOS" ;;
 		Windows_NT) os="Windows" ;;
 		*)          echo "Unknown platform" >&2
 	esac
 	echo $os
 }
+sources() {
+	set -xe
+	for dir in ecs ui
+	do
+		( cd lib/$dir && ./get --sources )
+	done
+}
 version() {
 	grep "define LIB_VERSION_STR" include/metadata.h | cut -d'"' -f2
 }
+_build_systemlibs() {
+	set -xe
+	( cd lib/platform && ./get --sources )
+	# SDL3 build-dep
+	sudo apt-get install build-essential cmake debhelper fcitx-libs-dev glslang-tools libasound2-dev libdbus-1-dev libdecor-0-dev libdrm-dev libegl-dev libgbm-dev libgl-dev libgles-dev libibus-1.0-dev libpipewire-0.3-dev libpulse-dev libsndio-dev libudev-dev liburing-dev libvulkan-dev libwayland-dev libx11-dev libxcursor-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxss-dev libxt-dev libxv-dev libxxf86vm-dev pkgconf wayland-protocols xxd graphviz doxygen
+	# missing libusb2-dev libusbhid-dev but build don't fail
+	( cd lib/platform/sdl3-deb/libsdl3-* && LANG=C dpkg-buildpackage -uc -us && rm -f libsdl3-doc* libsdl3-tests* )
+}
+_prebuilt_systemlibs() {
+	set -xe
+        rm -rf lib
+	zipname=build-dep-$(version)-SystemLibs-$1.zip
+        url=https://ludolpif.fr/pub/llss/artifacts/$zipname
+        [ -f $zipname ] || curl -o $zipname $url
+        unzip -q $zipname
+        rm -f $zipname
+}
+
 case $1 in
 	--build-dep) build_dep $2 ;;
 	--cflags) cflags $2 ;;
 	--ldflags) ldflags $2 ;;
 	--name) name $2 ;;
 	--prettyos) prettyos $2 ;;
+	--sources) sources $2 ;;
 	--version) version $2 ;;
-	*) echo "Usage $0 (--build-dep|--cflags|--ldflags|--prettyos|--name|--version) (Release|Debug)" >&2 ;;
-esac
+	*) echo "Usage $0 (--build-dep|--cflags|--ldflags|--name|--prettyos|--sources|--version) (Debug|Release|SystemLibs)" >&2 ;;
 
